/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package desarrollohumano;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class Menu extends javax.swing.JFrame {

    DefaultListModel listaPai = new DefaultListModel();
     //Declarando la lista de paises a usar
    Lista country = new Lista();
    Lista controlBandera = new Lista();
    //Contador de objetos
    static int contador = 1;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        EscrituraBinaria escritura = new EscrituraBinaria();

        try {
            controlBandera = escritura.leerBinario("banderas.bin");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPaises = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        menuBarra = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirItem = new javax.swing.JMenuItem();
        guardarItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boton1.setText("Ingresar Pais");
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
        });

        boton2.setText("Ingresar Estimadores");
        boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton2MouseClicked(evt);
            }
        });

        boton4.setText("Buscar o Eliminar Pais");
        boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton4MouseClicked(evt);
            }
        });
        boton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton4KeyPressed(evt);
            }
        });

        boton3.setText("Grafica Circular");

        boton5.setText("Estadisticas");

        boton6.setText("Grafica de Avance");

        jScrollPane1.setViewportView(listaPaises);

        jLabel1.setText("Paises Disponibles");

        jMenu1.setText("Archivo");

        abrirItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        abrirItem.setText("Abrir Binario");
        abrirItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirItemMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirItemMouseClicked(evt);
            }
        });
        abrirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirItemActionPerformed(evt);
            }
        });
        jMenu1.add(abrirItem);

        guardarItem.setText("Guardar Cambios");
        guardarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardarItemMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarItemMouseClicked(evt);
            }
        });
        jMenu1.add(guardarItem);

        menuBarra.add(jMenu1);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(boton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton1)
                    .addComponent(boton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton4)
                    .addComponent(boton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton5)
                    .addComponent(boton6))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirItemActionPerformed

    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
        // TODO add your handling code here:
        System.out.println("Antes de presionar el boton de ingreso la lista es: ");
        country.imprimirLista();
        System.out.println("La lista de control de banderas es:");
        controlBandera.imprimirLista();
        InCountry dia1 = new InCountry(this, country, controlBandera ,true);
        listaPai.clear();
        for(int i = 1 ; i <= country.getPosicion(); i++){
            String cad = "";
            cad = country.accesoAleatorio(i).getID() + "  " + country.accesoAleatorio(i).getName();
            listaPai.addElement(cad);
            this.listaPaises.setModel(listaPai);
        }
    }//GEN-LAST:event_boton1MouseClicked

    private void boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseClicked
         InEstimadores dia1 = new InEstimadores(this, country, true);
    }//GEN-LAST:event_boton2MouseClicked

    private void boton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton4KeyPressed

    private void boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseClicked
        // TODO add your handling code here:
        Busqueda dia2 = new Busqueda(this, country, true);
        listaPai.clear();
        for(int i = 1 ; i <= country.getPosicion(); i++){
            String cad = "";
            cad = country.accesoAleatorio(i).getID() + "  " + country.accesoAleatorio(i).getName();
            listaPai.addElement(cad);
            this.listaPaises.setModel(listaPai);
        }
    }//GEN-LAST:event_boton4MouseClicked

    private void abrirItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirItemMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser(".");
        int result = fc.showOpenDialog(this);
        if ( result == JFileChooser.APPROVE_OPTION){
            try {
                File f = fc.getSelectedFile();
                EscrituraBinaria escritura = new EscrituraBinaria();
                country = escritura.leerBinario(f.getAbsolutePath());
                controlBandera = escritura.leerBinario("banderas.bin");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } 
    }//GEN-LAST:event_abrirItemMouseClicked

    private void guardarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarItemMouseClicked
        // TODO add your handling code here:
        EscrituraBinaria escritura = new EscrituraBinaria();
        escritura.escribirBinario("paises.bin", country);
        escritura.escribirBinario("banderas.bin", controlBandera);
        System.out.println("Archivos Guardados");
        JOptionPane.showMessageDialog(rootPane, "Datos Guardados");
        
    }//GEN-LAST:event_guardarItemMouseClicked

    private void abrirItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirItemMousePressed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser(".");
        int result = fc.showOpenDialog(this);
        if ( result == JFileChooser.APPROVE_OPTION){
            try {
                File f = fc.getSelectedFile();
                EscrituraBinaria escritura = new EscrituraBinaria();
                country = escritura.leerBinario(f.getAbsolutePath());
                controlBandera = escritura.leerBinario("banderas.bin");
                EscrituraTexto es = new EscrituraTexto();
                Menu.contador = es.leerContador("contador.txt");
                System.out.println("El valor leido para contador es: " + Menu.contador);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_abrirItemMousePressed

    private void guardarItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarItemMousePressed
        // TODO add your handling code here:
        EscrituraBinaria escritura = new EscrituraBinaria();
        escritura.escribirBinario("paises.bin", country);
        escritura.escribirBinario("banderas.bin", controlBandera);
        System.out.println("Archivos Guardados");
        EscrituraTexto text = new EscrituraTexto("contador.txt", "No importa");
        text.escribirContador(Menu.contador);
        JOptionPane.showMessageDialog(rootPane, "Datos Guardados");
    }//GEN-LAST:event_guardarItemMousePressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirItem;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JMenuItem guardarItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaPaises;
    private javax.swing.JMenuBar menuBarra;
    // End of variables declaration//GEN-END:variables
}
